version: '3.0'

expectations:
  population_size: 10000

actions:

  
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-06-01 to 2021-12-01 by month" --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  create_notebook:
    run: python:latest python analysis/create_notebook.py
    outputs:
      moderately_sensitive:
        notebook: analysis/Test_Notebook.ipynb

  # generate_notebook:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/SRO_Notebook.ipynb --execute --to html --output-dir=/workspace/output/joined --ExecutePreprocessor.timeout=86400 --no-input
  #   needs: [create_notebook, calculate_rates, generate_study_population_practice_count]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/joined/SRO_Notebook.html

  # run_tests:
  #   run: python:latest python -m pytest --junit-xml=output/pytest.xml --verbose
  #   outputs:
  #     moderately_sensitive:
  #       log: output/pytest.xml
